### PR TITLE
Returns error when coordinates are malformed

### LINKED ISSUE #742: Get components definitions fails when one of components is unformatted
When requesting definitions for a list of components that includes an unformatted entry(for example:  "npm/npmjs/redie/0.3.0") the request failes for all components and returns uninformative error: 

`{
  "error": {
    "code": "500",
    "message": "An error has occurred",
    "innererror": {}
  }
}`

### PR DESCRIPTION
**Pull request by nellshamrell**
Fixes #742

One this is merged, if someone makes POST to `definitions` with a malformed component, like this:

```bash
curl -X POST "https://clearlydefined.io/definitions" -H "accept: application/json" -H "Content-Type: application/json" -d "[\"npm/npmjs/redie/0.3.0\",\"npm/npmjs/-/redie/0.3.0\"]"
```

They will receive a more useful error:

```bash
curl -X POST "https://clearlydefined.io/definitions" -H "accept: application/json" -H "Content-Type: application/json" -d "[\"npm/npmjs/redie/0.3.0\",\"npm/npmjs/-/redie/0.3.0\"]"

An error occured when trying to fetch coordinates for one of the components: Coordinates npm/npmjs/redie/0.3.0 appear to be malformed. Are they missing a namespace or revision?
```

### CODE REVIEW

File: business/definitionService.js [hunk 1]
```diff
@@ -72,7 +72,14 @@ class DefinitionService {
     if (get(existing, '_meta.schemaVersion') === currentSchema) {
       this.logger.info('computed definition available', { coordinates: coordinates.toString() })
       result = existing
-    } else result = await this.computeAndStore(coordinates)
+    } else {
+      try {
+        result = await this.computeAndStore(coordinates)
+        return this._trimDefinition(this._cast(result), expand)
+      } catch (err) {
+        throw new Error(err.message)
```
Comment (adrian-sufaru) [inline business/definitionService.js:80]: Does this do anything other than recreate the original Error? Not sure if the purpose is to hide the underlying call stack by overwriting from this point.

Comment (nellshamrell) [reply business/definitionService.js:80]: That's a good point, let me experiment a bit

Comment (nellshamrell) [reply business/definitionService.js]: Thank you! I was making this considerably more complicated than it had to be. I've fixed it up!

File: routes/definitions.js [hunk 2]
```diff
@@ -70,6 +70,28 @@ async function listDefinitions(request, response) {
   // if running on localhost, allow a force arg for testing without webhooks to invalidate the caches
   const force = request.hostname.includes('localhost') ? request.query.force || false : false
   const expand = request.query.expand === '-files' ? '-files' : null // only support '-files' for now
+  try {
```
Comment (jeffmcaffer) [inline routes/definitions.js:73]: Are these changes really related to this problem? I'm not a fan of this code being in the route (perhaps better in the service itself) but either way, it seems unrelated to the issue at hand

Comment (nellshamrell) [reply routes/definitions.js:73]: It is. The problem was we weren't capturing the the errors and returning them in a way that was useful to the user. I added this with the purpose of capturing the errors when they happen during a call and then returning them to the user. Otherwise it would just error out with a 500 whenever an error happened somewhere in the callstack.

Comment (nellshamrell) [reply routes/definitions.js:73]: I am happy to jump on a call and talk through this more if it would be useful.

Comment (adrian-sufaru) [reply routes/definitions.js:73]: This looks similar to the code in the next method, maybe we want to use a common function to do this consistently instead of duplicating?

Comment (nellshamrell) [reply routes/definitions.js:73]: What happened was I forgot to delete the original code when I moved it into the try catch block. It's fixed!

**Review by adrian-sufaru — APPROVED** [review]
